const overviewData = {
  projects: [
    {
      id: "PRJ-001",
      name: "Payments Platform",
      repos: [
        {
          name: "payment-services",
          pdfCount: 142,
          lastCommit: "03 Sep 2026",
          baseUrl: "https://bitbucket.org/acme/payment-services",
        },
        {
          name: "architecture-docs",
          pdfCount: 87,
          lastCommit: "01 Sep 2026",
          baseUrl: "https://bitbucket.org/acme/architecture-docs",
        },
        {
          name: "gateway-platform",
          pdfCount: 64,
          lastCommit: "28 Aug 2026",
          baseUrl: "https://bitbucket.org/acme/gateway-platform",
        },
      ],
    },
    {
      id: "PRJ-002",
      name: "Cloud Migration",
      repos: [
        {
          name: "aws-migration",
          pdfCount: 91,
          lastCommit: "04 Sep 2026",
          baseUrl: "https://bitbucket.org/acme/aws-migration",
        },
        {
          name: "legacy-documents",
          pdfCount: 53,
          lastCommit: "22 Aug 2026",
          baseUrl: "https://bitbucket.org/acme/legacy-documents",
        },
        {
          name: "cloud-governance",
          pdfCount: 63,
          lastCommit: "31 Aug 2026",
          baseUrl: "https://bitbucket.org/acme/cloud-governance",
        },
      ],
    },
    {
      id: "PRJ-003",
      name: "Identity & Access",
      repos: [
        {
          name: "auth-core",
          pdfCount: 76,
          lastCommit: "02 Sep 2026",
          baseUrl: "https://bitbucket.org/acme/auth-core",
        },
        {
          name: "identity-docs",
          pdfCount: 58,
          lastCommit: "30 Aug 2026",
          baseUrl: "https://bitbucket.org/acme/identity-docs",
        },
        {
          name: "access-gateway",
          pdfCount: 39,
          lastCommit: "25 Aug 2026",
          baseUrl: "https://bitbucket.org/acme/access-gateway",
        },
      ],
    },
  ],
  documents: [
    {
      id: 1,
      name: "Payment_Gateway_Architecture.pdf",
      path: "/docs/architecture/payment/Payment_Gateway_Architecture.pdf",
      project: "PRJ-001",
      repo: "payment-services",
      opens: 14,
    },
    {
      id: 2,
      name: "ISO8583_Message_Flow.pdf",
      path: "/docs/integration/iso8583/ISO8583_Message_Flow.pdf",
      project: "PRJ-001",
      repo: "payment-services",
      opens: 27,
    },
    {
      id: 3,
      name: "Payment_Service_Runbook.pdf",
      path: "/operations/runbooks/Payment_Service_Runbook.pdf",
      project: "PRJ-001",
      repo: "payment-services",
      opens: 19,
    },
    {
      id: 4,
      name: "PCI_DSS_Architecture.pdf",
      path: "/standards/security/PCI_DSS_Architecture.pdf",
      project: "PRJ-001",
      repo: "architecture-docs",
      opens: 31,
    },
    {
      id: 5,
      name: "Event_Driven_Payments.pdf",
      path: "/patterns/events/Event_Driven_Payments.pdf",
      project: "PRJ-001",
      repo: "architecture-docs",
      opens: 12,
    },
    {
      id: 6,
      name: "Gateway_Failover_Design.pdf",
      path: "/docs/resilience/Gateway_Failover_Design.pdf",
      project: "PRJ-001",
      repo: "gateway-platform",
      opens: 18,
    },
    {
      id: 7,
      name: "Merchant_Routing_Guide.pdf",
      path: "/docs/routing/Merchant_Routing_Guide.pdf",
      project: "PRJ-001",
      repo: "gateway-platform",
      opens: 9,
    },
    {
      id: 8,
      name: "AWS_Migration_Strategy.pdf",
      path: "/strategy/cloud/AWS_Migration_Strategy.pdf",
      project: "PRJ-002",
      repo: "aws-migration",
      opens: 42,
    },
    {
      id: 9,
      name: "Network_Architecture.pdf",
      path: "/architecture/network/Network_Architecture.pdf",
      project: "PRJ-002",
      repo: "aws-migration",
      opens: 34,
    },
    {
      id: 10,
      name: "Landing_Zone_Standards.pdf",
      path: "/standards/platform/Landing_Zone_Standards.pdf",
      project: "PRJ-002",
      repo: "aws-migration",
      opens: 16,
    },
    {
      id: 11,
      name: "Legacy_System_Inventory.pdf",
      path: "/discovery/inventory/Legacy_System_Inventory.pdf",
      project: "PRJ-002",
      repo: "legacy-documents",
      opens: 22,
    },
    {
      id: 12,
      name: "Mainframe_Exit_Plan.pdf",
      path: "/planning/modernisation/Mainframe_Exit_Plan.pdf",
      project: "PRJ-002",
      repo: "legacy-documents",
      opens: 11,
    },
    {
      id: 13,
      name: "Cloud_Tagging_Policy.pdf",
      path: "/policies/governance/Cloud_Tagging_Policy.pdf",
      project: "PRJ-002",
      repo: "cloud-governance",
      opens: 25,
    },
    {
      id: 14,
      name: "Production_Deployment_Guide.pdf",
      path: "/operations/deployment/Production_Deployment_Guide.pdf",
      project: "PRJ-002",
      repo: "cloud-governance",
      opens: 37,
    },
    {
      id: 15,
      name: "Authentication_Flow.pdf",
      path: "/docs/flows/Authentication_Flow.pdf",
      project: "PRJ-003",
      repo: "auth-core",
      opens: 45,
    },
    {
      id: 16,
      name: "API_Security_Standards.pdf",
      path: "/standards/api/API_Security_Standards.pdf",
      project: "PRJ-003",
      repo: "auth-core",
      opens: 33,
    },
    {
      id: 17,
      name: "Token_Rotation_Runbook.pdf",
      path: "/operations/security/Token_Rotation_Runbook.pdf",
      project: "PRJ-003",
      repo: "auth-core",
      opens: 20,
    },
    {
      id: 18,
      name: "Identity_Data_Model.pdf",
      path: "/architecture/data/Identity_Data_Model.pdf",
      project: "PRJ-003",
      repo: "identity-docs",
      opens: 17,
    },
    {
      id: 19,
      name: "Database_Architecture.pdf",
      path: "/architecture/database/Database_Architecture.pdf",
      project: "PRJ-003",
      repo: "identity-docs",
      opens: 26,
    },
    {
      id: 20,
      name: "Disaster_Recovery_Design.pdf",
      path: "/resilience/recovery/Disaster_Recovery_Design.pdf",
      project: "PRJ-003",
      repo: "access-gateway",
      opens: 29,
    },
    {
      id: 21,
      name: "Zero_Trust_Access_Model.pdf",
      path: "/architecture/security/Zero_Trust_Access_Model.pdf",
      project: "PRJ-003",
      repo: "access-gateway",
      opens: 38,
    },
  ],
  people: [
    {
      name: "John Smith",
      repo: "payment-services",
      commits: 72,
      pdfs: 46,
    },
    {
      name: "Sarah Wilson",
      repo: "architecture-docs",
      commits: 61,
      pdfs: 38,
    },
    {
      name: "Aisha Rahman",
      repo: "gateway-platform",
      commits: 48,
      pdfs: 29,
    },
    {
      name: "Michael Chen",
      repo: "aws-migration",
      commits: 54,
      pdfs: 41,
    },
    {
      name: "Emma O'Brien",
      repo: "legacy-documents",
      commits: 43,
      pdfs: 24,
    },
    {
      name: "Daniel Okafor",
      repo: "cloud-governance",
      commits: 67,
      pdfs: 35,
    },
    {
      name: "Priya Patel",
      repo: "auth-core",
      commits: 58,
      pdfs: 44,
    },
    {
      name: "Liam Murphy",
      repo: "identity-docs",
      commits: 39,
      pdfs: 31,
    },
    {
      name: "Sofia Almeida",
      repo: "access-gateway",
      commits: 51,
      pdfs: 33,
    },
  ],
};
