# Generated by Django 6.1 on 2026-08-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluenceConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('base_url', models.URLField(blank=True, max_length=2048)),
                ('auth_mode', models.CharField(default='bearer', max_length=32)),
                ('credential_source', models.CharField(choices=[('none', 'Not configured'), ('keyring', 'Operating-system credential store'), ('environment', 'Managed externally')], default='none', max_length=20)),
                ('connection_status', models.CharField(choices=[('not_configured', 'Not configured'), ('stored_unverified', 'Stored — not verified'), ('connected', 'Connected'), ('invalid_credential', 'Invalid credential'), ('access_denied', 'Access denied'), ('rate_limited', 'Rate limited'), ('unreachable', 'Unreachable'), ('unsupported_response', 'Unsupported response'), ('credential_store_unavailable', 'Credential store unavailable'), ('managed_externally', 'Managed externally'), ('configuration_error', 'Configuration error')], default='not_configured', max_length=32)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Confluence configuration',
                'verbose_name_plural': 'Confluence configuration',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='bookmark_manager_single_confluence_configuration')],
            },
        ),
    ]
