# Generated by Django 6.1 on 2026-08-25 17:22

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark_manager", "0002_bookmark_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="import_record_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="legacy_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="BookmarkImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("schema_version", models.CharField(default="legacy", max_length=32)),
                (
                    "source_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("total_records", models.PositiveIntegerField(default=0)),
                ("processed_records", models.PositiveIntegerField(default=0)),
                ("imported_records", models.PositiveIntegerField(default=0)),
                ("skipped_records", models.PositiveIntegerField(default=0)),
                ("failed_records", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("completed_with_failures", "Completed with failures"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("outcome", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("processed_records__lte", models.F("total_records"))
                        ),
                        name="bookmark_import_processed_within_total",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "processed_records__gte",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("imported_records"),
                                        "+",
                                        models.F("skipped_records"),
                                    ),
                                    "+",
                                    models.F("failed_records"),
                                ),
                            )
                        ),
                        name="bookmark_import_results_within_processed",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BookmarkImportFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_number", models.PositiveIntegerField()),
                ("page_id", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="bookmark_manager.bookmarkimportrun",
                    ),
                ),
            ],
            options={
                "ordering": ["record_number", "id"],
            },
        ),
        migrations.AddField(
            model_name="bookmark",
            name="import_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookmarks",
                to="bookmark_manager.bookmarkimportrun",
            ),
        ),
        migrations.CreateModel(
            name="SavedBookmarkView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "normalized_name",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("search_text", models.TextField(blank=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("sort", models.CharField(default="added_newest", max_length=64)),
                ("visible_columns", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["normalized_name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("normalized_name", ""), _negated=True),
                        name="bookmark_saved_view_name_not_blank",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "normalized_name",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["normalized_name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("normalized_name", ""), _negated=True),
                        name="bookmark_tag_normalized_name_not_blank",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="bookmark",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="bookmarks",
                to="bookmark_manager.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["favorite", "-saved_at"],
                name="bookmark_favorite_saved_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["pinned", "-saved_at"],
                name="bookmark_pinned_saved_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["availability_status", "-updated_at"],
                name="bookmark_avail_updated_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["-last_viewed_at", "-open_count"],
                name="bookmark_usage_viewed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("import_record_number__isnull", True),
                    ("import_record_number__gte", 1),
                    _connector="OR",
                ),
                name="bookmark_import_record_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmarkimportfailure",
            constraint=models.CheckConstraint(
                condition=models.Q(("record_number__gte", 1)),
                name="bookmark_import_failure_record_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmarkimportfailure",
            constraint=models.UniqueConstraint(
                fields=("import_run", "record_number"),
                name="bookmark_import_one_failure_per_record",
            ),
        ),
    ]
