# Generated by Django 6.1 on 2026-08-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark_manager", "0009_bookmark_refresh_failure"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="confluencepagenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outline_position__isnull", False), ("parent__isnull", True)),
                fields=("outline_position",),
                name="bmk_node_root_outline_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="confluencepagenode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outline_position__isnull", False), ("parent__isnull", False)),
                fields=("parent", "outline_position"),
                name="bmk_node_child_outline_uniq",
            ),
        ),
    ]
