# Generated by Django 6.1 on 2026-09-04 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('canonical_url', models.CharField(max_length=2048, unique=True)),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('project', models.CharField(db_index=True, max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('testing', 'Testing connection'), ('cloning', 'Cloning'), ('pulling', 'Pulling'), ('ready', 'Ready'), ('auth_required', 'Authentication required'), ('failed', 'Failed')], db_index=True, default='queued', max_length=24)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('pdf_count', models.PositiveIntegerField(default=0)),
                ('vsdx_count', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_pull_on', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('project', 'slug', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('vsdx', 'VSDX')], db_index=True, max_length=4)),
                ('relative_path', models.CharField(max_length=2048)),
                ('filename', models.CharField(db_index=True, max_length=500)),
                ('added_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('added_by', models.CharField(blank=True, db_index=True, max_length=255)),
                ('added_by_email', models.EmailField(blank=True, max_length=320)),
                ('commit_id', models.CharField(blank=True, max_length=64)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bitbucket.repository')),
            ],
            options={
                'ordering': ('-added_at', 'filename', 'pk'),
                'indexes': [models.Index(fields=['kind', 'added_at'], name='bb_doc_kind_added_idx')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'relative_path'), name='bitbucket_unique_document_path')],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=320)),
                ('identity_key', models.CharField(max_length=600)),
                ('pdf_commit_count', models.PositiveIntegerField(default=0)),
                ('last_pdf_commit_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='bitbucket.repository')),
            ],
            options={
                'ordering': ('-pdf_commit_count', 'name', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('repository', 'identity_key'), name='bitbucket_unique_contributor')],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('clone', 'Clone'), ('pull', 'Pull')], max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('auth_required', 'Authentication required'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=24)),
                ('scheduled_for', models.DateField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
                ('output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='bitbucket.repository')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('repository', 'operation', 'scheduled_for'), name='bitbucket_one_scheduled_pull_per_day')],
            },
        ),
    ]
