# Generated by Django 6.1 on 2026-08-25 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfluencePageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('provisional_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('space_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sibling_position', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata_updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='bookmark_manager.confluencepagenode')),
            ],
            options={
                'ordering': ['parent_id', 'sibling_position', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('url', models.URLField(max_length=2048)),
                ('space_name', models.CharField(blank=True, max_length=255)),
                ('space_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by_id', models.CharField(blank=True, max_length=255)),
                ('created_by_name', models.CharField(blank=True, max_length=500)),
                ('modified_by_id', models.CharField(blank=True, max_length=255)),
                ('modified_by_name', models.CharField(blank=True, max_length=500)),
                ('author_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('author_name', models.CharField(blank=True, max_length=500)),
                ('saved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('favorite', models.BooleanField(db_index=True, default=False)),
                ('pinned', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('notes_updated_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveBigIntegerField(default=0)),
                ('first_opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_viewed_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_refresh_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_change_detected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('availability_status', models.CharField(choices=[('active', 'Active'), ('not_found', 'Not found'), ('access_denied', 'Access denied'), ('auth_error', 'Authentication error'), ('refresh_error', 'Refresh error')], db_index=True, default='active', max_length=32)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error_message', models.CharField(blank=True, max_length=255)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('tree_node', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bookmark', to='bookmark_manager.confluencepagenode')),
            ],
            options={
                'ordering': ['-saved_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='confluencepagenode',
            index=models.Index(fields=['parent', 'sibling_position', 'title'], name='bookmark_node_tree_order'),
        ),
        migrations.AddConstraint(
            model_name='confluencepagenode',
            constraint=models.CheckConstraint(condition=models.Q(('page_id__isnull', False), ('provisional_key__isnull', False), _connector='OR'), name='bookmark_node_has_source_or_provisional_identity'),
        ),
        migrations.AddConstraint(
            model_name='confluencepagenode',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='bookmark_node_is_not_its_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.CheckConstraint(condition=models.Q(('page_id', ''), _negated=True), name='bookmark_page_id_is_not_blank'),
        ),
    ]
