# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark_manager", "0010_reuse_lowest_outline_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkimportfailure",
            name="source_url",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
