# Generated by Django 6.1 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark_manager", "0011_bookmarkimportfailure_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkcategory",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
