# Generated by Django 6.1 on 2026-08-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark_manager", "0014_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkrefreshrun",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("scheduled", "Scheduled"),
                    ("retry", "Scheduled retry"),
                ],
                db_index=True,
                default="manual",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="BookmarkRefreshSchedule",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_updates",
                        to="bookmark_manager.bookmarkrefreshrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "bookmark refresh schedule",
                "verbose_name_plural": "bookmark refresh schedule",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="bookmark_refresh_single_schedule"
                    )
                ],
            },
        ),
    ]
