# Generated by Django 6.1 on 2026-08-29 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_search', '0002_gitcommit_pdfdocument_and_history_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='content_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='extracted_character_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='extraction_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='extraction_error_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='extractor_version',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='first_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='index_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Indexed'), ('no_text', 'No readable text'), ('partial', 'Partially indexed'), ('failed', 'Index failed'), ('stale_error', 'Stale searchable text')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='index_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='indexed_git_blob_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='indexed_source_commit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='last_index_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PDFExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_git_blob_id', models.CharField(max_length=64)),
                ('target_source_commit', models.CharField(max_length=64)),
                ('target_relative_path', models.CharField(max_length=2048)),
                ('target_file_size', models.PositiveBigIntegerField(default=0)),
                ('target_extractor_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('interrupted', 'Interrupted'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('phase', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('hashing', 'Hashing'), ('extracting', 'Extracting'), ('publishing', 'Publishing'), ('completed', 'Completed')], default='queued', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('characters_extracted', models.PositiveBigIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('worker_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='bitbucket_search.pdfdocument')),
                ('repository_sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to='bitbucket_search.repositorysyncjob')),
            ],
            options={
                'ordering': ['requested_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PDFTextRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sha256', models.CharField(max_length=64)),
                ('extractor_version', models.CharField(max_length=64)),
                ('source_byte_size', models.PositiveBigIntegerField(default=0)),
                ('state', models.CharField(choices=[('ready', 'Indexed'), ('no_text', 'No readable text'), ('partial', 'Partially indexed')], max_length=16)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extracted_character_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('content_sha256', 'extractor_version'), name='bitbucket_unique_pdf_text_revision')],
            },
        ),
        migrations.CreateModel(
            name='PDFTextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('extracted_text', models.TextField(blank=True)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('extraction_state', models.CharField(choices=[('ready', 'Indexed'), ('no_text', 'No readable text'), ('failed', 'Extraction failed')], max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='bitbucket_search.pdftextrevision')),
            ],
            options={
                'ordering': ['page_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='indexed_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='bitbucket_search.pdftextrevision'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['lifecycle_state', 'index_state', 'repository'], name='bb_pdf_index_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfextractionjob',
            index=models.Index(fields=['status', 'requested_at'], name='bb_extract_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='pdfextractionjob',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='bitbucket_extraction_job_progress_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='pdfextractionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('queued', 'running'))), fields=('document',), name='bitbucket_one_active_extraction_job_per_pdf'),
        ),
        migrations.AddIndex(
            model_name='pdftextpage',
            index=models.Index(fields=['revision', 'page_number'], name='bb_pdf_page_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='pdftextpage',
            constraint=models.UniqueConstraint(fields=('revision', 'page_number'), name='bitbucket_unique_pdf_revision_page'),
        ),
        migrations.AddConstraint(
            model_name='pdftextpage',
            constraint=models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='bitbucket_pdf_page_number_gte_1'),
        ),
    ]
