# Generated by Django 6.1 on 2026-08-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_search', '0005_repository_sync_daily_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitbucketPeopleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('normalized_name', ''), _negated=True), name='bitbucket_people_group_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='BitbucketPeopleGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('normalized_person_name', models.CharField(editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bitbucket_search.bitbucketpeoplegroup')),
            ],
            options={
                'ordering': ['normalized_person_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'normalized_person_name'), name='bitbucket_unique_people_group_member'), models.CheckConstraint(condition=models.Q(('normalized_person_name', ''), _negated=True), name='bitbucket_people_member_name_not_blank')],
            },
        ),
    ]
