# Generated by Django 6.1 on 2026-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_search', '0008_git_activity_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorysyncjob',
            name='output_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='repositorysyncjob',
            name='output_log_truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repositorysyncjob',
            name='output_log_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repositorysyncjob',
            name='phase',
            field=models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('checking_connection', 'Checking connection'), ('cloning', 'Cloning'), ('fetching', 'Fetching'), ('updating', 'Updating working tree'), ('discovering', 'Discovering documents'), ('finalizing', 'Finalizing'), ('completed', 'Completed')], default='queued', max_length=32),
        ),
    ]
