# Generated by Django 6.1 on 2026-09-01 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitbucket_search", "0010_repository_refresh_and_removal"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorysyncjob",
            name="operation_log_truncated",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RepositoryOperationLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("git", "Git"),
                            ("catalogue", "Catalogue"),
                            ("indexing", "PDF indexing"),
                            ("worker", "Background worker"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=8,
                    ),
                ),
                ("phase", models.CharField(blank=True, max_length=32)),
                ("event", models.CharField(max_length=64)),
                ("message", models.CharField(max_length=1024)),
                ("progress", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("worker_pid", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "extraction_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_log_entries",
                        to="bitbucket_search.pdfextractionjob",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_log_entries",
                        to="bitbucket_search.bitbucketrepository",
                    ),
                ),
                (
                    "sync_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_log_entries",
                        to="bitbucket_search.repositorysyncjob",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["repository", "channel", "id"], name="bb_log_repo_channel_idx"
                    ),
                    models.Index(fields=["sync_job", "id"], name="bb_log_sync_cursor_idx"),
                    models.Index(fields=["extraction_job", "id"], name="bb_log_extract_cursor_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sync_job__isnull", False),
                            ("extraction_job__isnull", False),
                            _connector="OR",
                        ),
                        name="bitbucket_log_entry_has_job",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("progress__isnull", True), ("progress__lte", 100), _connector="OR"
                        ),
                        name="bitbucket_log_progress_lte_100",
                    ),
                ],
            },
        ),
    ]
