# Generated by Django 6.1 on 2026-09-02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bitbucket_search", "0011_repository_operation_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitbucketHTTPSCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.URLField(max_length=2048, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cloud_api_token", "Bitbucket Cloud API token"),
                            ("cloud_access_token", "Bitbucket Cloud access token"),
                            ("basic_token", "Username and access token"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "credential_source",
                    models.CharField(
                        choices=[
                            ("keyring", "Operating-system credential store"),
                            ("database", "Encrypted local database"),
                        ],
                        default="database",
                        max_length=20,
                    ),
                ),
                ("credential_ciphertext", models.TextField(blank=True, editable=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("stored_unverified", "Stored — not verified"),
                            ("connected", "Connected"),
                            ("invalid_credential", "Invalid credential"),
                        ],
                        default="stored_unverified",
                        max_length=32,
                    ),
                ),
                ("configured_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["origin"],
            },
        ),
    ]
