# Generated by Django 6.1 on 2026-09-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitbucket_search", "0014_repositorysyncjob_worker_retry_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitbucketStarredPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=255)),
                (
                    "normalized_person_name",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["normalized_person_name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("normalized_person_name", ""), _negated=True),
                        name="bitbucket_starred_person_name_not_blank",
                    )
                ],
            },
        ),
    ]
