# Generated by Django 6.1 on 2026-09-03 17:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbucket_search', '0016_pdfdocument_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFPipelineTuningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('mode', models.CharField(max_length=16)),
                ('action', models.CharField(choices=[('recommend', 'Recommend'), ('apply', 'Apply'), ('rollback', 'Rollback'), ('safety_override', 'Safety override')], max_length=24)),
                ('previous_target', models.PositiveSmallIntegerField()),
                ('proposed_target', models.PositiveSmallIntegerField()),
                ('reason_code', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('confidence', models.CharField(max_length=16)),
                ('observation_window_seconds', models.PositiveIntegerField()),
                ('evidence', models.JSONField(default=dict)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='pdfextractionjob',
            name='completion_kind',
            field=models.CharField(blank=True, choices=[('normal_publication', 'Normal publication'), ('cache_reuse', 'Cache reuse')], db_index=True, max_length=24),
        ),
        migrations.AddField(
            model_name='pdfextractionjob',
            name='publication_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfextractionjob',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfextractionjob',
            name='staged_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PDFPipelineRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=128, unique=True)),
                ('state', models.CharField(choices=[('healthy', 'Healthy'), ('retry_wait', 'Retry wait'), ('recovering', 'Recovering'), ('paused', 'Paused'), ('resume_requested', 'Resume requested'), ('recovering_half_open', 'Recovering half-open')], db_index=True, default='healthy', max_length=32)),
                ('episode_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('generation', models.PositiveBigIntegerField(default=0)),
                ('pause_generation', models.PositiveBigIntegerField(default=0)),
                ('reason_family', models.CharField(blank=True, max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('consecutive_failed_attempts', models.PositiveIntegerField(default=0)),
                ('lifetime_attempts', models.PositiveBigIntegerField(default=0)),
                ('pause_after_attempts', models.PositiveIntegerField(default=25)),
                ('first_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_backoff_seconds', models.PositiveIntegerField(default=0)),
                ('paused_reason', models.CharField(blank=True, max_length=500)),
                ('paused_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('popup_acknowledged_generation', models.PositiveBigIntegerField(default=0)),
                ('popup_claimed_generation', models.PositiveBigIntegerField(default=0)),
                ('resume_requested_at', models.DateTimeField(blank=True, null=True)),
                ('resume_idempotency_key_hash', models.CharField(blank=True, max_length=64)),
                ('resume_predecessor_generation', models.PositiveBigIntegerField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_outcome', models.CharField(blank=True, max_length=500)),
                ('active_attempt_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope'],
                'constraints': [models.CheckConstraint(condition=models.Q(('popup_acknowledged_generation__lte', models.F('pause_generation'))), name='bb_recovery_ack_lte_pause_gen'), models.CheckConstraint(condition=models.Q(('popup_claimed_generation__lte', models.F('pause_generation'))), name='bb_recovery_claim_lte_pause_gen')],
            },
        ),
        migrations.CreateModel(
            name='PDFPipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('repository_add', 'Repository added'), ('repository_refresh', 'Repository refresh'), ('refresh_all', 'Refresh all'), ('daily', 'Daily refresh'), ('recovery', 'Recovery'), ('reindex', 'Reindex')], db_index=True, default='repository_refresh', max_length=32)),
                ('state', models.CharField(choices=[('queued', 'Added to queue'), ('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete'), ('completed_with_errors', 'Completed with errors'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('accepted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accepted_repository_count', models.PositiveIntegerField(default=0)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['-accepted_at', '-id'],
                'indexes': [models.Index(fields=['state', '-accepted_at'], name='bb_pipeline_run_state_idx')],
            },
        ),
        migrations.CreateModel(
            name='PDFPipelineRunRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_state', models.CharField(choices=[('queued', 'Added to queue'), ('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete'), ('completed_with_errors', 'Completed with errors'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('phase', models.CharField(choices=[('queued', 'Added to queue'), ('checking_connection', 'Checking connection'), ('cloning', 'Cloning'), ('pulling', 'Pulling'), ('discovering', 'Discovering PDFs'), ('validating', 'Validating'), ('hashing', 'Hashing'), ('extracting', 'Extracting'), ('writing', 'Writing'), ('extracting_and_writing', 'Extracting + writing'), ('reusing_cached', 'Reusing cached text'), ('retry_wait', 'Waiting to retry'), ('recovering', 'Recovering'), ('completing', 'Completing'), ('paused', 'Paused'), ('complete', 'Complete'), ('completed_with_errors', 'Completed with errors'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('repository_revision', models.CharField(blank=True, max_length=64)),
                ('accepted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inventory_final', models.BooleanField(db_index=True, default=False)),
                ('inventory_final_at', models.DateTimeField(blank=True, null=True)),
                ('total_pdfs', models.PositiveIntegerField(default=0)),
                ('successful_pdfs', models.PositiveIntegerField(default=0)),
                ('permanent_failed_pdfs', models.PositiveIntegerField(default=0)),
                ('cancelled_pdfs', models.PositiveIntegerField(default=0)),
                ('remaining_pdfs', models.PositiveIntegerField(default=0)),
                ('unresolved_failures', models.PositiveIntegerField(default=0)),
                ('terminal_outcome', models.CharField(blank=True, choices=[('queued', 'Added to queue'), ('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete'), ('completed_with_errors', 'Completed with errors'), ('cancelled', 'Cancelled')], max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_run_memberships', to='bitbucket_search.bitbucketrepository')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_memberships', to='bitbucket_search.pdfpipelinerun')),
            ],
            options={
                'ordering': ['accepted_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pdfextractionjob',
            name='run_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to='bitbucket_search.pdfpipelinerunrepository'),
        ),
        migrations.AddField(
            model_name='repositorysyncjob',
            name='run_repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='bitbucket_search.pdfpipelinerunrepository'),
        ),
        migrations.CreateModel(
            name='TrustedRepositoryHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_origin', models.URLField(max_length=2048, unique=True)),
                ('hostname', models.CharField(db_index=True, max_length=253)),
                ('port', models.PositiveIntegerField(default=443)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname', 'port', 'id'],
                'constraints': [models.UniqueConstraint(fields=('hostname', 'port'), name='bitbucket_unique_trusted_host_port'), models.CheckConstraint(condition=models.Q(('port__gte', 1), ('port__lte', 65535)), name='bitbucket_trusted_host_port_range')],
            },
        ),
        migrations.CreateModel(
            name='PDFPipelineRecoveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('generation', models.PositiveBigIntegerField()),
                ('pause_generation', models.PositiveBigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('episode_opened', 'Episode opened'), ('attempt_started', 'Attempt started'), ('attempt_failed', 'Attempt failed'), ('attempt_succeeded', 'Attempt succeeded'), ('retry_scheduled', 'Retry scheduled'), ('paused', 'Paused'), ('resume_requested', 'Resume requested'), ('recovered', 'Recovered'), ('superseded', 'Superseded')], max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bitbucket_search.pdfpipelinerecovery')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['recovery', '-occurred_at'], name='bb_recovery_event_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pdfpipelinerunrepository',
            index=models.Index(fields=['run', 'lifecycle_state'], name='bb_pipeline_member_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfpipelinerunrepository',
            index=models.Index(fields=['repository', '-accepted_at'], name='bb_pipeline_repo_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='pdfpipelinerunrepository',
            constraint=models.UniqueConstraint(fields=('run', 'repository'), name='bitbucket_unique_pipeline_run_repository'),
        ),
    ]
