# Generated by Django 6.1 on 2026-08-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitbucketRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("canonical_remote_key", models.CharField(max_length=1024, unique=True)),
                ("remote_url", models.CharField(max_length=2048)),
                ("local_path", models.CharField(blank=True, max_length=1024)),
                ("default_branch", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("not_cloned", "Not cloned"),
                            ("queued", "Queued"),
                            ("cloning", "Cloning"),
                            ("fetching", "Fetching"),
                            ("updating", "Updating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("interrupted", "Interrupted"),
                            ("disabled", "Disabled"),
                            ("blocked_dirty", "Blocked by local changes"),
                        ],
                        db_index=True,
                        default="not_cloned",
                        max_length=32,
                    ),
                ),
                ("sync_progress", models.PositiveSmallIntegerField(default=0)),
                ("status_message", models.CharField(blank=True, max_length=500)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("last_error_summary", models.CharField(blank=True, max_length=500)),
                ("pdf_count", models.PositiveIntegerField(default=0)),
                ("vsdx_count", models.PositiveIntegerField(default=0)),
                ("document_bytes", models.PositiveBigIntegerField(default=0)),
                ("last_synced_commit", models.CharField(blank=True, max_length=64)),
                ("last_sync_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_successful_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("sync_progress__lte", 100)),
                        name="bitbucket_app_repository_progress_lte_100",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RepositorySyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(choices=[("clone", "Clone"), ("refresh", "Refresh")], max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("interrupted", "Interrupted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("validating", "Validating"),
                            ("cloning", "Cloning"),
                            ("fetching", "Fetching"),
                            ("updating", "Updating working tree"),
                            ("discovering", "Discovering documents"),
                            ("finalizing", "Finalizing"),
                            ("completed", "Completed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("status_message", models.CharField(blank=True, max_length=500)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_summary", models.CharField(blank=True, max_length=500)),
                ("source_commit", models.CharField(blank=True, max_length=64)),
                ("result_commit", models.CharField(blank=True, max_length=64)),
                ("requested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("worker_pid", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_jobs",
                        to="bitbucket.bitbucketrepository",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("progress__lte", 100)),
                        name="bitbucket_app_sync_job_progress_lte_100",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("queued", "running"))),
                        fields=("repository",),
                        name="bitbucket_app_one_active_job_per_repository",
                    ),
                ],
            },
        ),
    ]
