# Generated by Django 6.1 on 2026-09-03 00:00

from importlib import import_module

from django.db import migrations, models

_fts = import_module("bitbucket.migrations.0004_pdf_fts_indexes")
_drop_metadata_triggers = _fts.DROP_METADATA_FTS[:-1]
_create_metadata_triggers = _fts.CREATE_METADATA_FTS[2:]


class Migration(migrations.Migration):
    dependencies = [
        ("bitbucket", "0015_bitbucket_starred_person"),
    ]

    operations = [
        # SQLite rebuilds this table for a new indexed non-null field. Keep the
        # cross-table metadata triggers out of the rename window without dropping
        # the derived FTS table or its searchable rows.
        migrations.RunSQL(_drop_metadata_triggers, _create_metadata_triggers),
        migrations.AddField(
            model_name="pdfdocument",
            name="starred",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunSQL(_create_metadata_triggers, _drop_metadata_triggers),
    ]
