"use strict";
const bookmarkSeed = [
  [
    "Engineering handbook",
    "https://confluence.example.com/wiki/spaces/ENG/pages/100/Handbook",
    "Team conventions, processes and onboarding.",
    28,
    1,
  ],
  [
    "Platform architecture",
    "https://confluence.example.com/wiki/spaces/ENG/pages/101/Architecture",
    "Services, integrations and architecture decisions.",
    42,
    2,
  ],
  [
    "Release checklist",
    "https://confluence.example.com/wiki/spaces/OPS/pages/102/Release",
    "Everything to check before a production release.",
    17,
    3,
  ],
  [
    "Incident response",
    "https://confluence.example.com/wiki/spaces/OPS/pages/103/Incidents",
    "On-call responsibilities and recovery procedures.",
    0,
    null,
  ],
  [
    "API design standards",
    "https://confluence.example.com/wiki/spaces/ENG/pages/104/API",
    "Patterns for consistent, maintainable APIs.",
    12,
    6,
  ],
  [
    "Product roadmap",
    "https://confluence.example.com/wiki/spaces/PRODUCT/pages/105/Roadmap",
    "Upcoming milestones and planned improvements.",
    0,
    null,
  ],
  [
    "Web documentation",
    "https://developer.mozilla.org/en-US/docs/Web",
    "Reference guides for the web platform.",
    9,
    4,
  ],
  [
    "Accessibility guidelines",
    "https://www.w3.org/WAI/standards-guidelines/wcag/",
    "Build accessible interfaces.",
    0,
    null,
  ],
  [
    "Python documentation",
    "https://docs.python.org/3/",
    "Python language and standard library reference.",
    14,
    5,
  ],
  [
    "Git reference",
    "https://git-scm.com/docs",
    "Git commands and workflows.",
    3,
    15,
  ],
  [
    "Django documentation",
    "https://docs.djangoproject.com/en/stable/",
    "Django framework reference.",
    7,
    2,
  ],
  [
    "Architecture decisions",
    "https://confluence.example.com/wiki/spaces/ENG/pages/106/Decisions",
    "The reasoning behind technical choices.",
    5,
    8,
  ],
];
