# Generated by Django 6.1 on 2026-09-01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bitbucket_search", "0011_repository_operation_logs"),
        ("bookmark_manager", "0017_alter_notification_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemanticCorpusState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pdf_revision", "PDF revision"),
                            ("bookmark", "Bookmark"),
                        ],
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("generation", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["source_type"],
            },
        ),
        migrations.CreateModel(
            name="SemanticIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pdf_revision", "PDF revision"),
                            ("bookmark", "Bookmark"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("model_version", models.CharField(max_length=160)),
                ("chunker_version", models.CharField(max_length=64)),
                ("dimensions", models.PositiveSmallIntegerField()),
                ("centroid_vector", models.BinaryField()),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("character_count", models.PositiveBigIntegerField(default=0)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bookmark",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_index",
                        to="bookmark_manager.bookmark",
                    ),
                ),
                (
                    "pdf_revision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_index",
                        to="bitbucket_search.pdftextrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["source_type", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("bookmark__isnull", True),
                                ("pdf_revision__isnull", False),
                                ("source_type", "pdf_revision"),
                            ),
                            models.Q(
                                ("bookmark__isnull", False),
                                ("pdf_revision__isnull", True),
                                ("source_type", "bookmark"),
                            ),
                            _connector="OR",
                        ),
                        name="semantic_index_source_matches",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SemanticIndexJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pdf_revision", "PDF revision"),
                            ("bookmark", "Bookmark"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("target_content_hash", models.CharField(max_length=64)),
                ("target_model_version", models.CharField(max_length=160)),
                ("target_chunker_version", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("worker_pid", models.PositiveIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_summary", models.CharField(blank=True, max_length=500)),
                (
                    "bookmark",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_index_jobs",
                        to="bookmark_manager.bookmark",
                    ),
                ),
                (
                    "pdf_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_index_jobs",
                        to="bitbucket_search.pdftextrevision",
                    ),
                ),
            ],
            options={
                "ordering": ["requested_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="semantic_job_queue_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("bookmark__isnull", True),
                                ("pdf_revision__isnull", False),
                                ("source_type", "pdf_revision"),
                            ),
                            models.Q(
                                ("bookmark__isnull", False),
                                ("pdf_revision__isnull", True),
                                ("source_type", "bookmark"),
                            ),
                            _connector="OR",
                        ),
                        name="semantic_job_source_matches",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("pdf_revision__isnull", False),
                            ("status__in", ("queued", "running")),
                        ),
                        fields=("pdf_revision",),
                        name="semantic_one_active_pdf_job",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("bookmark__isnull", False),
                            ("status__in", ("queued", "running")),
                        ),
                        fields=("bookmark",),
                        name="semantic_one_active_bm_job",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SemanticChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("chunk_text", models.TextField()),
                ("text_hash", models.CharField(max_length=64)),
                ("vector", models.BinaryField()),
                ("character_count", models.PositiveIntegerField(default=0)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="semantic_search.semanticindex",
                    ),
                ),
            ],
            options={
                "ordering": ["index_id", "ordinal", "id"],
                "indexes": [
                    models.Index(
                        fields=["index", "page_number"],
                        name="semantic_chunk_page_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("index", "ordinal"),
                        name="semantic_unique_index_chunk",
                    ),
                ],
            },
        ),
    ]
